### ISSUE TITLE
Spinner throws an error and exits process on rebuild

### ISSUE THREAD

**Issue by acburdine** [denali-js/denali-cli#19]
Experiencing this error with latest released denali cli, running `denali server` in an app.

`denali server` builds the app and starts initially, but any rebuilds trigger this error, causing the process to exit:

```
A promise was rejected but did not have a .catch() handler:
Error: Spinner process failed to acknowledge a command on time: start(Building api)
    at Timeout.setTimeout (/Users/acburdine/Sites/tourdefours/api/node_modules/denali-cli/src/spinner.ts:38:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

/Users/acburdine/Sites/tourdefours/api/node_modules/denali-cli/src/spinner.ts:38
      reject(new Error(`Spinner process failed to acknowledge a command on time: ${ operation }(${ args.join(', ') })`))
             ^
Error: Spinner process failed to acknowledge a command on time: start(Building api)
    at Timeout.setTimeout (/Users/acburdine/Sites/tourdefours/api/node_modules/denali-cli/src/spinner.ts:38:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

The issue occurs in `denali server` but because it's erroring in the spinner I _think_ it's an issue with the CLI. Can move the issue over to denali if it's not an error here.

**Comment by acburdine** [comment]
Note: this is a pretty nasty issue to have because it means that I have to re-run `denali server` every time I make a change. Will investigate further.
