### ISSUE TITLE
Can't find file error when using `denali test --debug`

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali-cli#59]
My command output:

```sh
$ DEBUG=denali* denali test --debug
cli v0.1.4 [local] | denali v0.1.2 [local]
✔ denali-sockets build complete (8.761s)
===> Running denali-sockets tests ...
Debugger listening on ws://127.0.0.1:9229/2711c012-8750-4b47-996f-d96a6c1bc8c5
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
Error: ENOENT: no such file or directory, open '/Users/iradchenko/sandbox/denali-sockets/tmp/-dummy/test/**/*.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at CachingPrecompiler.precompileFile (/Users/iradchenko/sandbox/denali-sockets/node_modules/ava/lib/caching-precompiler.js:39:34)
    at babelConfigHelper.build.then.result (/Users/iradchenko/sandbox/denali-sockets/node_modules/ava/profile.js:88:35)
    at <anonymous>
Waiting for the debugger to disconnect...
```

Looks live ava does something with babel? I am using the TS addon in this addon.

Error:

```sh
VM128 index.js:30 Error: ENOENT: no such file or directory, open '/Users/iradchenko/sandbox/denali-sockets/tmp/-dummy/test/**/*.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at CachingPrecompiler.precompileFile (/Users/iradchenko/sandbox/denali-sockets/node_modules/ava/lib/caching-precompiler.js:39:34)
    at babelConfigHelper.build.then.result (/Users/iradchenko/sandbox/denali-sockets/node_modules/ava/profile.js:88:35)
    at <anonymous>
```

Without the `--debug` I get this:

```sh
$ DEBUG=denali* denali test
cli v0.1.4 [local] | denali v0.1.2 [local]
✔ denali-sockets build complete (10.244s)
===> Running denali-sockets tests ...

  7 passed
  1 known failure

   acceptance › default-blueprint-test › checks code with tslint

===> Tests passed 👍
```

(Interesting that eslint runs even though I deleted all the files and deps for it..)
(Ah, it's for the dummy app)

**Comment by davewasmer** [comment]
It looks like it's trying to open the file literally named `tmp/-dummy/test/**/*.js`. Sounds like something is passing a glob pattern into something that doesn't support glob patterns directly.

Does this happen on a fresh / blank addon?

**Comment by knownasilya** [comment]
Not 100% fresh or 100% blank. I can push it up so you can test.

**Comment by knownasilya** [comment]
https://github.com/knownasilya/denali-sockets
