### ISSUE TITLE
bug: chokes on outdated global npm links

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali-cli#8]
Basically if you have done `npm link` in a local project, and then removed the project, the cli dies in `find-plugins`

```
denali-cli v0.0.9 [local]
Error encountered while starting up denali-cli:
Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/ember-data-checkin'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at fs.readdirSync.reduce.map.filter (/Users/iradchenko/sandbox/denali/node_modules/find-plugins/index.js:76:27)
    at Array.filter (native)
    at findCandidatesInDir (/Users/iradchenko/sandbox/denali/node_modules/find-plugins/index.js:76:8)
    at Function.findPlugins [as default] (/Users/iradchenko/sandbox/denali/node_modules/find-plugins/index.js:29:58)
    at Object.findAddons [as default] (/Users/iradchenko/sandbox/denali/node_modules/denali-cli/src/find-addons.ts:40:27)
    at Object.run [as default] (/Users/iradchenko/sandbox/denali/node_modules/denali-cli/src/bootstrap.ts:42:26)
    at Object.<anonymous> (/Users/iradchenko/sandbox/denali/node_modules/denali-cli/src/bin/denali.ts:55:73)
    at Module._compile (module.js:570:32)
denali-cli v0.0.9 [local]
```

**Comment by knownasilya** [comment]
Would label it, but don't have access in this repo.

**Comment by knownasilya** [comment]
Even with 1.0.2, still fails.
